/*
    Question: Problem Statement Given a 2-dimensional matrix of size ‘N’ x ‘M’, rotate the elements of the matrix clockwise.

    For example: 
    Input Matrix: [ [ 1, 2, 3 ] 
                    [ 4, 5, 6 ] 
                    [ 7, 8, 9 ] ]

    Output Matrix: [ [ 4, 1, 2 ] 
                    [ 7, 5, 3 ] 
                    [ 8, 9, 6 ] ]

    The output matrix is generated by rotating the elements of the input matrix in a clockwise direction. Note that every element is rotated only once.

    link : https://www.codingninjas.com/codestudio/problems/rotate-matrix_8230774?challengeSlug=striver-sde-challenge&leftPanelTab=0
*/

import java.util.*;

public class RotateMatrixClockwise {
    public static void rotateMatrix(ArrayList<ArrayList<Integer>> mat, int n, int m) {
        
        int rowStart = 0, rowEnd = n;
        int colStart = 0, colEnd = m;
        int prev = 0, curr = 0;

        while (rowStart < rowEnd && colStart < colEnd) {

            if(rowStart+1 == rowEnd || colStart + 1 == colEnd) break;
            
            prev = mat.get(rowStart + 1).get(colStart);

            for (int i = colStart; i < colEnd; i++) {
                curr = mat.get(rowStart).get(i);
                mat.get(rowStart).set(i, prev);
                prev = curr;
            }
            rowStart++;

            for (int i = rowStart; i < rowEnd; i++) {
                curr = mat.get(i).get(colEnd-1);
                mat.get(i).set(colEnd-1, prev);
                prev = curr;
            }
            colEnd--;
            if (rowStart < rowEnd) {
                for (int i = colEnd-1; i >= colStart; i--) {
                    curr = mat.get(rowEnd-1).get(i);
                    mat.get(rowEnd-1).set(i, prev);
                    prev = curr;
                }
            }
            rowEnd--;

            if (colStart < colEnd) {
                for (int i = rowEnd-1; i >= rowStart; i--) {
                    curr = mat.get(i).get(colStart);
                    mat.get(i).set(colStart, prev);
                    prev = curr;
                }
            }
            colStart++;
        }
    }
}